import { LooseObject, DataReturn, MetaCandle, RunStrategy } from "../../../types/global";
export declare function runStrategy(options: RunStrategy): Promise<DataReturn | {
    name: string;
    strategyName: string;
    symbols: string[];
    permutationCount: any;
    params: LooseObject;
    startTime: number;
    endTime: number;
    txFee: number;
    slippage: number;
    startingAmount: number;
    multiResults: any;
    isMultiValue: boolean;
    isMultiSymbol: boolean;
    historicalDataName?: undefined;
    candleMetaData?: undefined;
    candles?: undefined;
    runMetaData?: undefined;
    allOrders?: undefined;
    allWorths?: undefined;
} | {
    name: string;
    historicalDataName: string;
    candleMetaData: MetaCandle;
    candles: any;
    strategyName: string;
    params: LooseObject;
    startTime: number;
    endTime: number;
    txFee: number;
    slippage: number;
    startingAmount: number;
    runMetaData: any;
    allOrders: any;
    allWorths: any;
    symbols?: undefined;
    permutationCount?: undefined;
    multiResults?: undefined;
    isMultiValue?: undefined;
    isMultiSymbol?: undefined;
}>;
