export {
  RunStrategy,
  BuySell,
  BuySellReal,
  GetCandles,
  Candle,
  MetaCandle,
  BTH,
  OrderBook,
  ImportCSV,
  StrategyResult,
  GetStrategyResult,
  StrategyResultMulti,
  Order,
  Worth,
  RunMetaData,
  StrategyMeta,
  LooseObject,
  ScanAction,
  AssetAmounts,
  RunStrategyResultMulti,
  RunStrategyResult
} from '../src/helpers/interfaces'
